### ISSUE TITLE
Transporting Kerbals into craft can hang/crash the game

### ISSUE THREAD

**Issue by MrKiel** [mmoench/KSTS#1]
Hello!

I ran some testing this evening based on problems reported in the release thread, and found a problem. It's quite serious, in certain conditions the game will hang and/or crash. 

I'm fairly sure I can reproduce it. I have a partially crewed station in LKO, and under certain conditions the game will hang if I use KSTS to transport crew to it. Having a spaceplane docked to a station seems to cause problems - I'm not sure if it's having trouble determining the root part or if it's something else. 

There are also parts in the station with crew capacity that is only available when the modules are deployed. The modules were deployed at the time of the problem, but KSTS may be having problems determining whether a part has crew capacity under these conditions. 

I've made a copy of the save file (attached), I'm pretty sure I can reproduce it if you require further information. 

[errorgame.zip](https://github.com/mmoench/KSTS/files/559453/errorgame.zip)

**Comment by MrKiel** [comment]
I believe the problem is in TargetVesssel.cs at line 252

```
do
{
    foreach (ProtoCrewMember crewMember in targetPart.protoModuleCrew)
        {
        if (seatIdx == crewMember.seatIdx) { seatIdx++; seatSwitched = true; }
        }
}
while (seatSwitched);
```

foreach() inside a while(), the while() loop will not end if seatSwitched is ever set to true

**Comment by mmoench** [comment]
Yes, you are right, I inadvertently added this bug in the last release when I tried to solve an issue with seats getting used multiple times. I've fixed the issue in the new release.
Thank you for the report.
