### ISSUE TITLE
Complex Orbit Reference Vessel list filters reference target SMA with Profile Altitude.

### ISSUE THREAD

**Issue by mostlikely4r** [mmoench/KSTS#4]
In the deployment tab under complex orbit the list of vessels under 'select reference vessel' are filtered by the max altitude of the mission profile. However the vessel SMA is used instead of the vessel altitude.

Example:
Mission profile: Test payload (Max Altitude: 675,000m) [Max SMA: 1,275,000m]
Vessel shown: Ship 1 (Altitude: 74,000m) [SMA: 674,000m]
Vessel not shown: Ship 2 (Altitude: 80,000m) [SMA: 680,000m]

**Comment by mmoench** [comment]
This should be fixed in the current 1.6 release. Thank you for the report.
