### ISSUE TITLE
Deployed vessel parts have uid = 0

### ISSUE THREAD

**Issue by mostlikely4r** [mmoench/KSTS#5]
When deploying a vessel all parts have uid = 0. This causes referential problems while docking making undocking impossible.

These uid's need to be filled by the same counter the game uses if possible.

An example uid generated in the game is 2310102047 however the value (range) seems to be trivial (values as low as 1 seem to work fine) as long as they are unique. This means that using an internal KSTS counter (starting at 1, increasing by 1 each part that is created by KSTS) might suffice.

**Comment by mmoench** [comment]
I've fixed this issue in the upcoming release. Each part will get its own uid when a new vessel is created.
Thank you for the report.
