### ISSUE TITLE
Fuel Lines/Struts not Connected

### ISSUE THREAD

**Issue by TheRhodanist** [mmoench/KSTS#6]
It seems that Fuel Lines and Struts are not Connected when a Vessel is Deployed/Constructed via KSTS, the Source-Node is there, it just does not seem to have a connection to the Target Part, wich prevents proper Fuel-Flow from External Tanks
(very nice mod btw.)

**Comment by mmoench** [comment]
Hm, I see. I will take a look at this. Thank you for the report.

**Comment by mmoench** [comment]
This issue should be fixed now in release 1.7, thanks again.
