### ISSUE TITLE
Higher Orbit with less payload

### ISSUE THREAD

**Issue by Fumblesneeze** [mmoench/KSTS#8]
This is a suggestion, sorry if I'm bothering you, I prefer using github over the forums.

So basically when I run a KSTS mission with a payload capacity of 20 tons and only transport 8, it should be able to reach a way higher orbit, as is usually the case with real life missions delivering different weight cargo to different orbits using the same rocket configuration.

The maximum orbit height could be estimated (for calculation we would need the weight of the upper/delivery stage, which could be recorded but would be a breaking change for old saves).

I could try some estimates if you're interested in this.

**Comment by mmoench** [comment]
Hm, I can see what you are going for, but I believe it is better to simply record a second launch-profile with the same vessel.
